---
- hosts: all
  tasks:
    - name: install nginx
      apt: pkg=nginx state=installed update_cache=true
      notify:
      - start nginx
  
  handlers:
    - name: start nginx
      service: name=nginx state=started
